### ISSUE TITLE
Gray out previous/next days in calendar view

### ISSUE THREAD

**Issue by Qtipshooter** [Qtipshooter/taskbook-SWE#60]
I think it would be nice to gray out the days of the previous and next month by a little bit so that they don't all look the same.

_Originally posted by @sagarsubedi in https://github.com/Qtipshooter/taskbook-SWE/pull/55#r770088127_

**Comment by sagarsubedi** [comment]
@Qtipshooter @ebradd5 actually has the code in the CSS file to do this. I did some digging and it looks like the reason it was not working is that in the file calendar-style.css line 94, the names of the classes should be .prev-date and .next-date (not .prev-days and .next-days). If you correct the misspelled classes name, the days or previous and next months will have a background of primary-white and text-color of primary-black. Now, because all other days have a white background and primary-white is a bluish-white, you could choose to make it a bit more gray or some other color which might make it more clear that the prev and next months' days are being seperated, but the code will work soon as you correct the classes names.
